GET http://localhost:5000/request

###

GET http://localhost:5000/request/192.168.112.12

###
PATCH http://localhost:5000/request/acc/1/Rasa%20Pasir

###
PATCH http://localhost:5000/request/dec/1

###
GET http://localhost:5000/recipes

###
GET http://localhost:5000/recipes/18

###
POST http://localhost:5000/recipes/create
Content-Type: application/json

{
    "nama_resep" : "Rasa Coklat"
}
###

POST http://localhost:5000/recipes/ingredients/1
Content-Type: application/json

{
    "bahan_baku" : "Pasir",
    "jumlah" : 7
}

###

GET http://localhost:5000/stok/Coklat

###
POST http://localhost:5000/stok/add
Content-Type: application/json

{
    "bahan_baku" : "Apel",
    "stok" : 130
}

###

POST http://localhost:5000/stok/updateStok
Content-Type: application/json

{
    "bahan_baku" : "Maizena",
    "stok" : 199
}

###
DELETE http://localhost:5000/recipes/ingredients/1/Gula