GET http://localhost:5000/request

###
GET http://localhost:5000/posts
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJuYW1lIjoiVGltIiwiaWF0IjoxNjM3ODk4MDYyLCJleHAiOjE2Mzc4OTgwOTJ9.e_F-ezquf7KWf62tjpoXsvlLm0twbvqGoSNlVLob0q4

###
DELETE http://localhost:5000/logout

{
    "token": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJuYW1lIjoiSmFjayIsImlhdCI6MTYzNzg5NjI1N30.um41N8OBxhgJWzWhgbBVrPJcITOb0CX0XnZgZah4ixo"
}

###
POST http://localhost:5000/login
Content-Type: application/json

{
    "username": "Tim"
}

###
POST http://localhost:5000/token
Content-Type: application/json

{
    "token": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJuYW1lIjoiVGltIiwiaWF0IjoxNjM3ODk4MDYyfQ.mI4vzo1nteFhnmZdrP_5WkiwGpJv54F-sgsw9C7my9c"
}

###
GET http://localhost:5000/request/192.168.112.12

###
PATCH http://localhost:5000/request/acc/1/Rasa%20Pasir

###
PATCH http://localhost:5000/request/dec/1

###
GET http://localhost:5000/recipes

###
GET http://localhost:5000/recipes/18

###
POST http://localhost:5000/recipes/create
Content-Type: application/json

{
    "nama_resep" : "Rasa Coklat"
}
###

POST http://localhost:5000/recipes/ingredients/1
Content-Type: application/json

{
    "bahan_baku" : "Pasir",
    "jumlah" : 7
}

###

GET http://localhost:5000/stok/Coklat

###
POST http://localhost:5000/stok/add
Content-Type: application/json

{
    "bahan_baku" : "Apel",
    "stok" : 130
}

###

POST http://localhost:5000/stok/updateStok
Content-Type: application/json

{
    "bahan_baku" : "Maizena",
    "stok" : 199
}

###
DELETE http://localhost:5000/recipes/ingredients/1/Gula